openapi: 3.0.3
info:
  title: PA Submission API
  description: |-
    Submission API is used for submitting the draft personal Auto Quotes.
  version: 1.0.0

servers:
  - url: https://localhost/pa/quote/v1
tags:
  - name: personal auto quote
    description: personal auto quote
paths:
  /submit:
    post:
      tags:
        - personal auto quote
      summary: submit a draft quote
      description: submit a draft personal auto quote
      operationId: submitPAQuote
      requestBody:
        description: quote submission request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/submission'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/submissionResponse'   
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        '405':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
components:
  schemas:
    submission:
      type: object
      properties:
        submissionId:
          type: string
        quoteNumber:
          type: string
        productName:
          type: string
        riskState:
          type: string
        agent:
          $ref: '#/components/schemas/agent'
        primaryInsured:
          $ref: '#/components/schemas/primaryInsured'
        vehicles:
          type: array
          items:
            $ref: "#/components/schemas/vehicle"
        policyCoverages:
          type: array
          items:
            $ref: "#/components/schemas/coverage"
    vehicle:
      type: object
      properties:
        vehicleId:
          type: string
        model:
          type: string
        vin: 
          type: string
        makeYear:
          type: string
        drivers:
          type: array
          items:
            $ref: "#/components/schemas/driver"
        vehicleCoverages:
          type: array
          items:
            $ref: "#/components/schemas/coverage"
    coverage:
      type: object
      properties:
        coverageName:
          type: string
        coverageCode:
          type: string
        coverageLimit:
          type: string
        deductible:
          type: string
    driver:
      type: object
      properties:
        driverId:
          type: string
        driverName:
          type: string
        driverLicenseInfo:
          $ref: "#/components/schemas/driverLicenseInfo"
    agent:
      type: object
      properties:
        agentName:
          type: string
        contractNumber:
          type: string
        producerSubCode:
          type: string
        stateProducerId:
          type: string
        producerRoleCode:
          type: string
    primaryInsured:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        middleName:
          type: string
        dateOfBirth:
          type: string
        gender:
          type: string
        address:
          $ref: '#/components/schemas/address'
        driverLicenseInfo:
          $ref: '#/components/schemas/driverLicenseInfo'
    address:
      type: object
      properties:
        addressLine1: 
          type: string
        addressLine2:
          type: string
        street:
          type: string
        state:
          type: string
    driverLicenseInfo:
      type: object
      properties:
        lincenseNumber:
          type: string
        licenseStateCode:
          type: string
        licenseStatus:
          type: string
    submissionResponse:
      type: object
      properties:
        submissionId: 
          type: string
        status:
          type: string
    errorResponse:
      type: object
      properties:
        errorCode: 
          type: string
        errorDescription:
          type: string
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header